### ISSUE TITLE
Could I just use the .v file in rtl  to build my core?

### ISSUE THREAD

**Issue by yosan-0369** [ZipCPU/dblclockfft#6]
Hello, thank for your open source providing. But I am not sure where and how to use the code to build the core, could I use code:block to run the code and build the core in Win10? Actually I try to use the .v file of rtl folder directly, but it does not work because I think some .hex file is lacked. Could you give me some suggestions to use the source? Thank you.

**Comment by ZipCPU** [comment]
Try this ZIP file.  It should have the (missing) hex files attached.

[dblclockfft.rtl.zip](https://github.com/ZipCPU/dblclockfft/files/4932793/dblclockfft.rtl.zip)

They're not kept in the repository simply because of the expectation that the RTL as written isn't likely to satisfy anyone's purposes without being rebuilt.  Once you rebuild the RTL, you get a choice of FFT size, data widths, multiply implementations, and more.  The HEX files would then be rebuilt at that time to match your needs.  The RTL files that exist are more for demonstration--so you can look over the logic and see if it's something you are interested in or not.

I will point out that others have managed to build the core generator under windows.  There are a [couple of hiccups when doing so](https://github.com/ZipCPU/dblclockfft/blob/master/sw/fftgen.cpp#L58-L84): the lstat command isn't supported under windows, and mkdir doesn't use two arguments under windows like it does under Linux.  Other than those two issues, my understanding is that you should be able to build it fairly well.

Dan

**Comment by yosan-0369** [comment]
> Try this ZIP file.  It should have the (missing) hex files attached.
> dblclockfft.rtl.zip
> They're not kept in the repository simply because of the expectation that the RTL as written isn't likely to satisfy anyone's purposes without being rebuilt.  Once you rebuild the RTL, you get a choice of FFT size, data widths, multiply implementations, and more.  The HEX files would then be rebuilt at that time to match your needs.  The RTL files that exist are more for demonstration--so you can look over the logic and see if it's something you are interested in or not.
> I will point out that others have managed to build the core generator under windows.  There are a couple of hiccups when doing so: the lstat command isn't supported under windows, and mkdir doesn't use two arguments under windows like it does under Linux.  Other than those two issues, my understanding is that you should be able to build it fairly well.
> Dan

Thank you very much. I will try to run the rtl and check the simulation result for FFT core design studying. And then I will try to deal with the problem under windows.
